name: Accessible DatePicker
author: mashalla
category: Widgets
current: 1.2
tags: [Datepicker, Calendar, Picker, Accessible, Screen Reader]
#docs: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
demo: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html


sources:
  - "Source/Picker.js"
  - "Source/Picker.Attach.js"
  - "Source/Picker.Date.js"
  - "Source/Picker.Date.Range.js"
  - "Source/Locale.en-US.DatePicker.js"
  - "Source/Locale.cs-CZ.DatePicker.js"
  - "Source/Locale.de-DE.DatePicker.js"
  - "Source/Locale.fr-FR.DatePicker.js"
  - "Source/Locale.it-IT.DatePicker.js"
  - "Source/Locale.nl-NL.DatePicker.js"
  - "Source/Locale.pl-PL.DatePicker.js"
  - "Source/Locale.ru-RU.DatePicker.js"
