
name: Accessible DatePicker
author: mashalla
current: 1.0
category: Widgets
tags: [Datepicker, Calendar, Picker]
license: MIT

sources:
  - "Source/Picker.js"
  - "Source/Picker.Attach.js"
  - "Source/Picker.Date.js"
  - "Source/Picker.Date.Range.js"
  - "Source/Locale.en-US.DatePicker.js"
  - "Source/Locale.cs-CZ.DatePicker.js"
  - "Source/Locale.de-DE.DatePicker.js"
  - "Source/Locale.fr-FR.DatePicker.js"
  - "Source/Locale.it-IT.DatePicker.js"
  - "Source/Locale.nl-NL.DatePicker.js"
  - "Source/Locale.pl-PL.DatePicker.js"
  - "Source/Locale.ru-RU.DatePicker.js"
